name: MemoriesOfTime-GameCore
main: cn.lanink.gamecore.GameCore
version: "1.4.1.1-PM1E-SNAPSHOT"
api: ["Nukkit-PM1E"]
load: STARTUP
authors: ["LT_Name", "iGxnon"]
softdepend:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"