name: MemoriesOfTime-GameCore
main: cn.lanink.gamecore.GameCore
version: "1.6.13-PNX-SNAPSHOT"
api: ["1.0.0"]
load: STARTUP
authors: ["LT_Name", "iGxnon"]
softdepend:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"