name: MemoriesOfTime-GameCore
main: cn.lanink.gamecore.GameCore
version: "1.2.0-PM1E-SNAPSHOT"
api: ["Nukkit-PM1E"]
load: STARTUP
author: "LT_Name"
softdepend:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"