name: MemoriesOfTime-GameCore
main: cn.lanink.gamecore.GameCore
version: "1.5.5.0-PM1E"
api: ["Nukkit-PM1E"]
load: STARTUP
authors: ["LT_Name", "iGxnon"]
softdepend:
  - "ScoreboardPlugin"
  - "ScoreboardAPI"
  - "Tips"